# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_default: light

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo link in bio theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: false

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Me'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
