name = "Academic"
license = "MIT"
licenselink = "https://github.com/gcushen/hugo-academic/blob/master/LICENSE.md"
description = "A one page personal theme for academic staff and students."
homepage = "https://github.com/gcushen/hugo-academic"
tags = ["academic", "portfolio", "responsive", "student", "personal", "university", "blog", "minimal"]
features = ["biography", "academic interests", "research publication system", "blog"]
min_version = 0.15

[author]
  name = "George Cushen"
  homepage = "http://www.cushen.me"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
