[build]
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.1"
  GO_VERSION = "1.21.5"
  NODE_VERSION = "21.1.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
