# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo blog theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

footer:
  copyright:
    notice: 'Â© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: github-dark
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
