blank_issues_enabled: false
contact_links:
  - name: Troubleshooting Guide
    url: https://wowchemy.com/docs/faq/
    about: Solve common issues fast.
  - name: Questions and Discussions
    url: https://github.com/wowchemy/wowchemy-hugo-modules/discussions
    about: Please ask and answer questions here.
  - name: Chat with the Community
    url: https://discord.gg/z8wNYzb
    about: Join the Wowchemy Community on Discord.
