name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  update:
    if: github.repository_owner == 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - uses: HugoBlox/gh-action-updater@v1
        with:
          feed-url: https://hugoblox.com/blog/index.xml
          readme-section: news
          branch: main
