# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/customization/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

seo:
  site_type: Person
  local_business_type: ''
  org_name: ''
  description: ''
  twitter: ''

# Site header

header:
  navbar:
    enable: false

# Site footer

footer:
  copyright:
    notice: 'Â© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  privacy_pack: false

require_isotope: false

marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
